# use generic language
language: shell

os:
  - linux
  - osx

# ignored on osx
dist: bionic

# ignored on linux
osx_image: xcode9.4 # current default

# specify global envs and jobs
env:
  global:
    - EMU_FLAVOR=google_apis # ignore "default" case
  # define full matrix of SYS x ABI and comment-out or exclude invalid entries
  jobs:
    - SYS=29 ABI=x86_64
    - SYS=29 ABI=x86
    - SYS=29 ABI=armeabi-v7a
    # - SYS=28

# config jobs
jobs:
  fast_finish: true
  exclude:
    - os: osx
      env: SYS=29 ABI=armeabi-v7a
  allow_failures:
    - env: SYS=29 ABI=x86

script: echo "Done"