#    +-----------+--------------------+--------------------+
#    | API Level |     Code Name      | Android OS version |
#    +-----------+--------------------+--------------------+
#    |        29 | 10                 |                 10 |
#    |        28 | Pie                |                  9 |
#    |        27 | Oreo               |                8.1 |
#    |        26 | Oreo               |  (dropped arm) 8.0 |
#    |        25 | Nougat             |                7.1 |
#    |        24 | Nougat             |                7.0 |
#    |        23 | Marshmallow        |                6.0 |
#    |        22 | Lollipop           |                5.1 |
#    |        21 | Lollipop           |                5.0 |
#    |        20 | Not released       |                    |
#    |        19 | Kitkat             |                4.4 |
#    |        18 | Jellybean          |                4.3 |
#    |        17 | Jellybean          |                4.2 |
#    |        16 | Jellybean          |                4.1 |
#    |        15 | Ice Cream Sandwich |                4.0 |
#    |        14 | Not Released       |                    |
#    |        13 | Not Released       |                    |
#    |        12 | Not Released       |                    |
#    |        11 | Not Released       |                    |
#    |        10 | Gingerbread        |                2.3 |
#    +-----------+--------------------+--------------------+
# "https://en.wikipedia.org/wiki/Android_(operating_system)#Platform_information"

# use generic language
language: shell

os:
  - linux
#  - osx # x86 emulators require HAXM accelerator so removing for now.
         # see https://travis-ci.org/mmcc007/test_emulators/jobs/606234640#L899
         # (Flutter tests can be run on the iOS simulator.)

# ignored on osx
dist: bionic

# ignored on linux
#osx_image: xcode9.4 # current default

# specify global envs and jobs
env:
  global:
    - ANDROID_TOOLS=4333796 # android-28
    - ANDROID_HOME=${HOME}/android-sdk
    - GRAVIS="https://raw.githubusercontent.com/DanySK/Gravis-CI/master/"
    - JDK="1.8" # used while running sdkmanager, otherwise uses default JDK
    - TOOLS=${ANDROID_HOME}/tools
    # PATH order is incredibly important. e.g. the 'emulator' script exists in more than one place!
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
    - FLUTTER_CHANNEL=stable
    - FLUTTER_VERSION=1.9.1+hotfix.6-${FLUTTER_CHANNEL}
    - FLUTTER_HOME=${HOME}/flutter
    - export PATH=${HOME}/.pub-cache/bin:${PATH}
    - export PATH=${FLUTTER_HOME}/bin:${FLUTTER_HOME}/bin/cache/dart-sdk/bin:${PATH}

  # define full matrix of APIxABIxGOOGLE_APIS and comment-out invalid entries
  # (see "sdkmanager --list --verbose| grep ^system-images" for full list)
  jobs:
    - API=29 ABI=x86_64 GOOGLE_APIS=google_apis_playstore
    - API=29 ABI=x86    GOOGLE_APIS=google_apis_playstore
    - API=29 ABI=x86_64 GOOGLE_APIS=google_apis
    - API=29 ABI=x86    GOOGLE_APIS=google_apis

    - API=28 ABI=x86_64 GOOGLE_APIS=google_apis_playstore
    - API=28 ABI=x86    GOOGLE_APIS=google_apis_playstore
    - API=28 ABI=x86_64 GOOGLE_APIS=google_apis
    - API=28 ABI=x86    GOOGLE_APIS=google_apis

    - API=28 ABI=x86 GOOGLE_APIS=default
    - API=27 ABI=x86_64 GOOGLE_APIS=default
#    - API=26 ABI=x86_64 GOOGLE_APIS=default # Hanging: flutter doctor: Scanning for devices is taking a long time...
    - API=26 ABI=x86 GOOGLE_APIS=default
    - API=25 ABI=x86_64 GOOGLE_APIS=default
    - API=24 ABI=x86_64 GOOGLE_APIS=default
    - API=24 ABI=x86_64 GOOGLE_APIS=default JDK="1.11"
    - API=23 ABI=x86_64 GOOGLE_APIS=default
    - API=22 ABI=x86_64 GOOGLE_APIS=default
    - API=21 ABI=x86_64 GOOGLE_APIS=default
    # API=20  -- not released
    - API=19 ABI=x86_64 GOOGLE_APIS=default # sdkmanager: Failed to find system-images
#    - API=19 ABI=armeabi-v7a GOOGLE_APIS=default # Emulator does not start
    - API=18 ABI=x86_64 GOOGLE_APIS=default
    - API=18 ABI=x86
    - API=17 ABI=x86_64 GOOGLE_APIS=default
#    - API=17 ABI=x86 # flutter test hangs
    - API=16 ABI=x86_64 GOOGLE_APIS=default
#    - API=16 ABI=x86 AUDIO=-no-audio # flutter test hangs
#    - API=15 ABI=x86_64 GOOGLE_APIS=default # sdkmanager: Failed to find system-images
    # API=14 -- not released
    # API=13 -- not released
    # API=12 -- not released
    # API=11 -- not released
#    - API=10 ABI=x86_64 GOOGLE_APIS=default # sdkmanager: Failed to find system-images

#jobs:
#  fast_finish: true  # We can report success without waiting for jobs that we
#                     # allow / expect to fail.
#  include:
#    - env: API=24 JDK="1.11"
#  allow_failures:
#    - env: API=16 ABI=x86 AUDIO=-no-audio # flutter test hangs
#    - env: API=17 ABI=x86 # flutter test hangs
#    - env: API=18 ABI=x86 # flakey: gradlew fails sometimes during test
                          # "Could not load compiled classes for settings file"
#    - env: API=24 JDK="1.11"
#    - os: osx
  # (The test stage is implicit, add other stages here.)

before_install:
  # fix timezone warning on osx
#  - if [ $TRAVIS_OS_NAME == "osx" ]; then sudo ln -sf /usr/share/zoneinfo/US/Pacific /etc/localtime; fi

  # Set up KVM
  - |
    if [ $TRAVIS_OS_NAME == "linux" ]; then
      # Install dependencies
      sudo apt-get -y --no-install-recommends install bridge-utils libpulse0 libvirt-bin qemu-kvm virtinst ubuntu-vm-builder > /dev/null
      # add travis user to groups
      sudo adduser $USER libvirt
      sudo adduser $USER kvm
    fi

  # Set up JDK 8 for Android SDK
  - curl "${GRAVIS}.install-jdk-travis.sh" --output ~/.install-jdk-travis.sh
  - export TARGET_JDK="${JDK}"
  - JDK="1.8"
  - source ~/.install-jdk-travis.sh

  # Set up Android SDK
  - |
    if [ $TRAVIS_OS_NAME == "osx" ]; then
#      wget -q "https://dl.google.com/android/repository/sdk-tools-darwin-$ANDROID_TOOLS.zip" -O android-sdk-tools.zip
    else
      wget -q "https://dl.google.com/android/repository/sdk-tools-linux-$ANDROID_TOOLS.zip" -O android-sdk-tools.zip
    fi
  - unzip -q android-sdk-tools.zip -d ${ANDROID_HOME}
  - rm android-sdk-tools.zip

  # Avoid harmless sdkmanager warning
  - mkdir ~/.android
  - echo 'count=0' > ~/.android/repositories.cfg

  # Accept licenses before installing components, no need to echo y for each component
  - yes | sdkmanager --licenses >/dev/null

install:
  # Download SDK tools
  - sdkmanager "platform-tools" >/dev/null
  - sdkmanager "tools" >/dev/null # A second time per Travis docs, gets latest versions
  - sdkmanager "build-tools;28.0.3" >/dev/null # Implicit gradle dependency - gradle drives changes
  - sdkmanager "platforms;android-$API" >/dev/null # We need the API of the emulator we will run
  - sdkmanager "platforms;android-28" >/dev/null # We need the API of the current compileSdkVersion from gradle.properties
  - sdkmanager "emulator" >/dev/null
  - sdkmanager "extras;android;m2repository" >/dev/null
  - sdkmanager "system-images;android-$API;$GOOGLE_APIS;$ABI" >/dev/null # install our emulator

  # Create an Android emulator
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$API;$GOOGLE_APIS;$ABI" -c 10M --device "Nexus 6P"
  - EMU_PARAMS="-verbose -no-snapshot -no-window -camera-back none -camera-front none -selinux permissive -qemu -m 2048"
  # Disable acceleration for osx
#  - if [ $TRAVIS_OS_NAME == "osx" ]; then EMU_PARAMS="${EMU_PARAMS} -no-accel"; fi
  - EMU_COMMAND="emulator"
  - |
    if [[ $ABI =~ "x86" ]]; then
      EMU_COMMAND="emulator-headless"
    fi
  # This double "sudo" monstrosity is used to have Travis execute the
  # emulator with its new group permissions and help preserve the rule
  # of least privilege.
  - sudo -E sudo -u $USER -E bash -c "${ANDROID_HOME}/emulator/${EMU_COMMAND} -avd test ${AUDIO} ${EMU_PARAMS} &"

  # install flutter (while emulator is starting)
  - |
    if [ $TRAVIS_OS_NAME == "osx" ]; then
#      wget --quiet --output-document=flutter.zip https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/macos/flutter_macos_v${FLUTTER_VERSION}.zip && unzip -qq flutter.zip -d $(dirname ${FLUTTER_HOME}) && rm flutter.zip
    else
      sudo apt-get install -y --no-install-recommends lib32stdc++6 libstdc++6 > /dev/null
      wget --quiet --output-document=flutter.tar.xz https://storage.googleapis.com/flutter_infra/releases/${FLUTTER_CHANNEL}/linux/flutter_linux_v${FLUTTER_VERSION}.tar.xz && tar xf flutter.tar.xz -C $(dirname ${FLUTTER_HOME}) && rm flutter.tar.xz
    fi

  # Wait for emulator to be ready
  - ./script/android-wait-for-emulator.sh
  - adb shell input keyevent 82 &

  # Switch back to our target JDK version to build and run tests
  - JDK="${TARGET_JDK}"
  - source ~/.install-jdk-travis.sh

  - flutter doctor -v

script:
  - cd flutter_app; flutter driver lib/main.dart

#before_cache:
#  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
#  - curl "${GRAVIS}.clean_gradle_cache.sh" --output ~/.clean_gradle_cache.sh
#  - bash ~/.clean_gradle_cache.sh
#
#cache:
#  directories:
#    - $HOME/.gradle/caches/
#    - $HOME/.gradle/wrapper/